name = "Vanilla Plus"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "49b26e39ed0c855ee0eea6c23e9f9e826be5c5923b1670f76096a4026e3aed16"

[versions]
fabric = "0.14.21"
minecraft = "1.19.2"
