name = "Valkyiren Plus"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f436c308e01fa37a840d968ce2ba53bfd9f5369af27821f72552b6a7f3cb40e2"

[versions]
forge = "40.2.14"
minecraft = "1.18.2"
