name = "Valkyiren Plus"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3c1ec0708e417bf12f212095d49b1f37ed23df2791e3556f647dea95b8e247f0"

[versions]
forge = "40.2.14"
minecraft = "1.18.2"
