name = "Vanilla Plus"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8894f6e491ab13871ee5f8cd25fef15940c654818bd778c951ac50def60e2305"

[versions]
fabric = "0.14.21"
minecraft = "1.19.2"
