name = "Vanilla Plus"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0bf37e0cbfbeb450c119bb396391b45aad5f92c3714e3638107b545d63e0af89"

[versions]
fabric = "0.14.21"
minecraft = "1.19.2"
