name = "Valkyiren Plus"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7293561e8e1ef7c2683b8cd90a5fe3bd63465af14625492b1513675e4ce2afbc"

[versions]
forge = "40.2.14"
minecraft = "1.18.2"
