name = "ViveCraft"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2fc7f55748e8a2e6bb780c455249b10f786c729d46426c9b98a7b72dded9e931"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
