name = "ViveCraft"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c393cc0bffbd82027f40748e2f0437787ad14894dd7fa496baa1d337135ef74e"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
