name = "ViveCraft"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a4cc65c11a0de8683b5ccc9ebfbe4e2f375171e5616987fa1ce6a9c4874bd0f9"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
