name = "ViveCraft"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "250953c6b755c38aeeab37f342499edde61ec52e984867c74250fda306c11167"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
