name = "ViveCraft"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b13c28ad15bca96d82c7bdee5674d96d98f27b2033cf565ed855dd2a1aeab0e9"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
