name = "Valkyiren Plus"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8fe72ec54eebfe042ce9c8283ed9527329bd90d93c222cf20253819639d067bc"

[versions]
forge = "40.2.14"
minecraft = "1.18.2"
