name = "Valkyiren Plus"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "12761bc07cb1b825e69f807bc3a76767a17722ad32bfe50476a74513988fea49"

[versions]
forge = "40.2.14"
minecraft = "1.18.2"
